mat <- read.table("Planaria_dge.txt.gz")
dim(mat)
mat[1:5,1:5]
ann <- read.table("Planaria_annotation.txt")
ann <- read.table("Planaria_annotation.txt", sep=",")
dim(ann)
head(ann)
pca_coords <- read.table("Planaria_PCA.txt")
head(pca_coords)
dim(pca_coords)
pseudotime <- read.table("Planaria_pseudotime.txt")
head(pseudotime)
cdat <- data.frame(cell_type1=ann, pseudo=pseudotime)
colnames(pca_coords) <- paste("PC", 1:50, sep="")
cdat <- cbined(cdat, pca_coords)
cdat <- cbind(cdat, pca_coords)
head(cdat)
head(rownames(mat))
head(colnames(mat))
colnames(mat)
thing <- colnames(mat)
strsplit(thing, "_")
sample <- lapply(strsplit(thing, "_"), function(a){a[1]})
head(sample)
sample <- unlist(sample)
table(sample)
cdat$sample <- sample
head(cdat)
require("SingleCellExperiment")
obj <- SingleCellExperiment(assays=list(counts=mat), colData=cdat)
rownames(cdat) <- colnames(mat)
?SingleCellExperiment
obj <- SingleCellExperiment(assay=list(counts=mat), colData=cdat)
dim(mat)
dim(cdat)
class(mat)
require("Matrix")
Matrix(mat)
Matrix(as.matrix(mat))
MAT <- Matrix(as.matrix(mat))
dim(MAT)
obj <- SingleCellExperiment(assays=list(counts=mat), colData=cdat, rowData=data.frame(id=rownames(mat)))
obj <- SingleCellExperiment(assays=list(counts=MAT), colData=cdat, rowData=data.frame(id=rownames(mat)))
saveRDS(obj, "Planaria.rds")
savehistory("Planaria_hist.R")
devtools::install_github(repo = "hhoeflin/hdf5r")
devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
x <- read.table("Planaria_velocyto_loom.loom.gz")
dim(obj)
table(obj$cell_type1)
obj
head(colData(obj)
)
table(obj$V1)
source("Planaria.R")
